### ISSUE TITLE
No data issue during warping

### ISSUE THREAD

**Issue by t-hackwood** [ubarsc/rios#115]
Hey guys, 

I've been getting an error when warping two rasters on different grids on-the-fly, specifically gdal is giving "RuntimeError: Too few arguments for '-srcnodata'.", full traceback below. 

The error was resolved by reverting back to rios 1.4.17. I can provide files to replicate issue if needed.

Traceback (most recent call last):
  File "/home/tim/dentata/test/RiosBasic.py", line 46, in <module>
    applier.apply(heightCover, infiles, outfiles, controls=controls)
  File "/home/tim/miniforge3/envs/devENV/lib/python3.12/site-packages/rios/applier.py", line 774, in apply
    rtn = apply_singleCompute(userFunction, infiles, outfiles,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/miniforge3/envs/devENV/lib/python3.12/site-packages/rios/applier.py", line 843, in apply_singleCompute
    inputs = readBlockAllFiles(infiles, workinggrid,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/miniforge3/envs/devENV/lib/python3.12/site-packages/rios/imagereader.py", line 63, in readBlockAllFiles
    arr = readBlockOneFile(blockDefn, symbolicName, seqNum, filename,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/miniforge3/envs/devENV/lib/python3.12/site-packages/rios/imagereader.py", line 85, in readBlockOneFile
    (ds, bandObjList) = openForWorkingGrid(filename, workinggrid,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/miniforge3/envs/devENV/lib/python3.12/site-packages/rios/imagereader.py", line 345, in openForWorkingGrid
    warpOptions = gdal.WarpOptions(format="VRT", outputBounds=outBounds,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/miniforge3/envs/devENV/lib/python3.12/site-packages/osgeo/gdal.py", line 1115, in WarpOptions
    return (GDALWarpAppOptions(new_options), callback, callback_data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/miniforge3/envs/devENV/lib/python3.12/site-packages/osgeo/gdal.py", line 8987, in __init__
    _gdal.GDALWarpAppOptions_swiginit(self, _gdal.new_GDALWarpAppOptions(*args))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Too few arguments for '-srcnodata'.

Cheers!

**Comment by neilflood** [comment]
Hi @t-hackwood 

How depressing..... :-)

I may ask for those files, but before I do that, a few questions.

- How many bands in each input file?
- Do the input files have null values set in the file?
- If so, is this set for all bands?
- What datatypes are the files?

**Comment by t-hackwood** [comment]
Hi @neilflood

- Both are 6 bands
- Both have null values as -9999 for all bands
- data type of both files are float64

**Comment by neilflood** [comment]
OK, thanks. I will investigate. Leave it with me.

**Comment by neilflood** [comment]
Could you attach the output of gdalinfo for each file?

**Comment by t-hackwood** [comment]
Here you go:

[dem_info.txt](https://github.com/user-attachments/files/17051095/dem_info.txt)
[veg_info.txt](https://github.com/user-attachments/files/17051097/veg_info.txt)

**Comment by neilflood** [comment]
I can't see any problem. I think I am going to need the actual files :-(

Probably best not to attach these on github, so can you get them to me directly?
And also whatever controls settings you are using?

**Comment by t-hackwood** [comment]
No worries Neil!

Sam has passed on your email to me a so I'll send you an email with the data and rios code I've used :)

**Comment by t-hackwood** [comment]
After further investigation, it seems that this issue was with GDAL in my initial conda environment. RIOS 2.0.4 is working as expected for me now. Thanks @neilflood  and @gillins  for the assistance!

**Comment by t-hackwood** [comment]
closed without comment accidentally...

**Comment by t-hackwood** [comment]
After further investigation, it seems that this issue was with GDAL in my initial conda environment. RIOS 2.0.4 is working as expected for me now. Thanks @neilflood and @gillins for the assistance!

**Comment by neilflood** [comment]
Excellent, thank you :-)
