### ISSUE TITLE
error when installing

### ISSUE THREAD

**Issue by ghost** [ubarsc/rios#24]
Hello,

I'm getting this error whilst installing as in the readme file:

AttributeError: module 'rios' has no attribute 'RIOS_VERSION'

Any help would be greatly appreciated.

Cheers!

**Comment by neilflood** [comment]
Hi,

You will need to provide a lot more information. This is definitely not normal behaviour. 

The file rios/\_\_init__.py contains the symbol RIOS_VERSION. If that is not present, then something is seriously wrong.

If you still need help, could you provide the following.

1. What operating system are you working on?
2. How did you install RIOS? (provide the command you used)
3. How did you install its dependencies?
4. What is in the file rios/\_\_init__.py?

**Comment by gillins** [comment]
Closing as nothing was heard back from original poster (who has since deleted their account)
