### ISSUE TITLE
UnsupportedOperation: fileno

### ISSUE THREAD

**Issue by timea-kl** [ubarsc/rios#25]
Hi,

I've run into the below error when the raster inputs have different extent, I am running it from spyder (python 3). Any advice appreciated. Thanks 

![image](https://user-images.githubusercontent.com/46553005/84245315-6f796880-ab37-11ea-8ccf-6066ad18d60b.png)

**Comment by neilflood** [comment]
So, the first thing to note is that you will get an error if the images are not on the same grid, unless you specify one as the reference grid (see ApplierControls.setReferenceImage, or setReferencePixgrid). This enables RIOS to resample the other images to match that one. So, first question is - have you specified a reference image?

Having said that, it looks like the error report about this is itself causing an error. So the next question is - have you modified the loggingstream (e.g. with ApplierControls.setLoggingStream) ? It looks like it has a 'stdout' object which is not equivalent to sys.stdout. 

This might be something which spyder has modified, so the next test would be to run it outside spyder, and see if you get the same problem. I don't use spyder myself, so not sure exactly how it handles capturing stdout/stderr. However, lots of people use it, so I presume it mostly works. 

If all these things are OK, then could you describe how you installed RIOS and GDAL? It looks like you used conda - did you get all packages from the same channel?

**Comment by timea-kl** [comment]
Thanks, apparently the problem is with spyder, it was running straight from python without any error. Also doing a bit of digging into the issue I saw many people had similar problem with spyder. 
Thanks for the support and for rios :). I think we can close this!
