### ISSUE TITLE
update dtype aliases in imageio

### ISSUE THREAD

**Issue by rdenham** [ubarsc/rios#51]
For numpy 1.24.0, the deprecation for the aliases np.object, np.bool, np.float, np.complex, np.str, and np.int  expired (introduces NumPy 1.20). 

This means that in recent versions of numpy you'll get errors like:

```
AttributeError: module 'numpy' has no attribute 'bool'
```

Perhaps the authors could update the mapping in `imageio.py` to look like:

```python
dataTypeMapping = [
    (numpy.uint8, gdalconst.GDT_Byte),
    (numpy.bool_, gdalconst.GDT_Byte),
    (numpy.int16, gdalconst.GDT_Int16),
    (numpy.uint16, gdalconst.GDT_UInt16),
    (numpy.int32, gdalconst.GDT_Int32),
    (numpy.uint32, gdalconst.GDT_UInt32),
    (numpy.single, gdalconst.GDT_Float32),
    (numpy.float_, gdalconst.GDT_Float64)
]
```

So that the original alias `numpy.bool` becomes `numpy.bool_`.  Same for `numpy.float`. I think `bool` and `float` would also work.

Probably there are other ways too, but this approach seems to be the one with minimal effort and should not change the behaviour of the existing code.

**Comment by neilflood** [comment]
Thanks @rdenham 
Good point. Yes, we will update with something like that. Stay tuned......

**Comment by neilflood** [comment]
@rdenham 
There is now a new release of rios-1.4.14, which fixes this problem. Thank you for letting us know. 

Just FYI, python-fmask had similar problems, so there is now a new version 0.5.8 of that, too.

**Comment by rdenham** [comment]
thanks. Closed by https://github.com/ubarsc/rios/pull/52

**Comment by gillins** [comment]
Also a tuiview 1.2.11 with a fix FWIW.
